//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServerWeb.Resources.Views.AdminPromotion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminPromotionString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminPromotionString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalServerWeb.Resources.Views.AdminPromotion.AdminPromotionString", typeof(AdminPromotionString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion list.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount percent.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount type.
        /// </summary>
        public static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount value.
        /// </summary>
        public static string DiscountValue {
            get {
                return ResourceManager.GetString("DiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit food promotion.
        /// </summary>
        public static string EditFoodPromotion {
            get {
                return ResourceManager.GetString("EditFoodPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit invoice promotion.
        /// </summary>
        public static string EditInvoicePromotion {
            get {
                return ResourceManager.GetString("EditInvoicePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit promotion.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add.
        /// </summary>
        public static string ErrorCannotAdd {
            get {
                return ResourceManager.GetString("ErrorCannotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete.
        /// </summary>
        public static string ErrorCannotDelete {
            get {
                return ResourceManager.GetString("ErrorCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit.
        /// </summary>
        public static string ErrorCannotEdit {
            get {
                return ResourceManager.GetString("ErrorCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either start date or end date is not accepted.
        /// </summary>
        public static string ErrorDateWrong {
            get {
                return ResourceManager.GetString("ErrorDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date.
        /// </summary>
        public static string ErrorEndDateAfter {
            get {
                return ResourceManager.GetString("ErrorEndDateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested promotion not found.
        /// </summary>
        public static string ErrorPromotionNotFound {
            get {
                return ResourceManager.GetString("ErrorPromotionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully.
        /// </summary>
        public static string InfoAddSuccess {
            get {
                return ResourceManager.GetString("InfoAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully.
        /// </summary>
        public static string InfoDeleteSuccess {
            get {
                return ResourceManager.GetString("InfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successfully.
        /// </summary>
        public static string InfoEditSuccess {
            get {
                return ResourceManager.GetString("InfoEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no promotions.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string NumberOrdinary {
            get {
                return ResourceManager.GetString("NumberOrdinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PromotionDescription {
            get {
                return ResourceManager.GetString("PromotionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion name.
        /// </summary>
        public static string PromotionName {
            get {
                return ResourceManager.GetString("PromotionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion list.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
