//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServerWeb.Resources.Views.Kitchen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KitchenString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KitchenString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalServerWeb.Resources.Views.Kitchen.KitchenString", typeof(KitchenString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        public static string CheBien {
            get {
                return ResourceManager.GetString("CheBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DangCheBien.
        /// </summary>
        public static string DangCheBien {
            get {
                return ResourceManager.GetString("DangCheBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaXong.
        /// </summary>
        public static string DaXong {
            get {
                return ResourceManager.GetString("DaXong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string DonViTinh {
            get {
                return ResourceManager.GetString("DonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HetCheBien.
        /// </summary>
        public static string HetCheBien {
            get {
                return ResourceManager.GetString("HetCheBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string KhuVuc {
            get {
                return ResourceManager.GetString("KhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaChiTietOrder.
        /// </summary>
        public static string MaChiTietOrder {
            get {
                return ResourceManager.GetString("MaChiTietOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string MaOrder {
            get {
                return ResourceManager.GetString("MaOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhapSoLuongCheBien.
        /// </summary>
        public static string NhapSoLuongCheBien {
            get {
                return ResourceManager.GetString("NhapSoLuongCheBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhapSoLuongHet.
        /// </summary>
        public static string NhapSoLuongHet {
            get {
                return ResourceManager.GetString("NhapSoLuongHet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhapSoLuongXong.
        /// </summary>
        public static string NhapSoLuongXong {
            get {
                return ResourceManager.GetString("NhapSoLuongXong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhucVu.
        /// </summary>
        public static string PhucVu {
            get {
                return ResourceManager.GetString("PhucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaty.
        /// </summary>
        public static string SoLuong {
            get {
                return ResourceManager.GetString("SoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food name.
        /// </summary>
        public static string TenMon {
            get {
                return ResourceManager.GetString("TenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string TuyChon {
            get {
                return ResourceManager.GetString("TuyChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        public static string Xong {
            get {
                return ResourceManager.GetString("Xong", resourceCulture);
            }
        }
    }
}
