//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServerWeb.Resources.Views.AdminOrder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminOrderString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminOrderString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalServerWeb.Resources.Views.AdminOrder.AdminOrderString", typeof(AdminOrderString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel status.
        /// </summary>
        public static string CancelStatus {
            get {
                return ResourceManager.GetString("CancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CancelStatusNo {
            get {
                return ResourceManager.GetString("CancelStatusNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cancel detail.
        /// </summary>
        public static string CancelStatusTitle {
            get {
                return ResourceManager.GetString("CancelStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CancelStatusYes {
            get {
                return ResourceManager.GetString("CancelStatusYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no order detail information.
        /// </summary>
        public static string DetailNoData {
            get {
                return ResourceManager.GetString("DetailNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order detail.
        /// </summary>
        public static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish processing.
        /// </summary>
        public static string FinishProcessing {
            get {
                return ResourceManager.GetString("FinishProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food name.
        /// </summary>
        public static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock processing.
        /// </summary>
        public static string LockProcessing {
            get {
                return ResourceManager.GetString("LockProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orders.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string NumberOrdinary {
            get {
                return ResourceManager.GetString("NumberOrdinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor name.
        /// </summary>
        public static string ProcessorName {
            get {
                return ResourceManager.GetString("ProcessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity allowed.
        /// </summary>
        public static string QuantityAllowed {
            get {
                return ResourceManager.GetString("QuantityAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity required.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving.
        /// </summary>
        public static string Serving {
            get {
                return ResourceManager.GetString("Serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order list.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait processing.
        /// </summary>
        public static string WaitProcessing {
            get {
                return ResourceManager.GetString("WaitProcessing", resourceCulture);
            }
        }
    }
}
