//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServerWeb.Resources.Views.AdminReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminReportString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminReportString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalServerWeb.Resources.Views.AdminReport.AdminReportString", typeof(AdminReportString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ChooseEndDate {
            get {
                return ResourceManager.GetString("ChooseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose month.
        /// </summary>
        public static string ChooseMonth {
            get {
                return ResourceManager.GetString("ChooseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose report.
        /// </summary>
        public static string ChooseReport {
            get {
                return ResourceManager.GetString("ChooseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ChooseStartDate {
            get {
                return ResourceManager.GetString("ChooseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print report.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily report.
        /// </summary>
        public static string RevenueDayReport {
            get {
                return ResourceManager.GetString("RevenueDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly report.
        /// </summary>
        public static string RevenueMonthReport {
            get {
                return ResourceManager.GetString("RevenueMonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period report.
        /// </summary>
        public static string RevenuePeriodReport {
            get {
                return ResourceManager.GetString("RevenuePeriodReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue report.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
