//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalServerWeb.Resources.Views.AdminVoucher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminVoucherString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminVoucherString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalServerWeb.Resources.Views.AdminVoucher.AdminVoucherString", typeof(AdminVoucherString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add automatically.
        /// </summary>
        public static string AddManyVoucherDetail {
            get {
                return ResourceManager.GetString("AddManyVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new voucher.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new code.
        /// </summary>
        public static string AddVoucherDetail {
            get {
                return ResourceManager.GetString("AddVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount value.
        /// </summary>
        public static string DiscountValue {
            get {
                return ResourceManager.GetString("DiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit voucher.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit code.
        /// </summary>
        public static string EditVoucherDetail {
            get {
                return ResourceManager.GetString("EditVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add.
        /// </summary>
        public static string ErrorCannotAdd {
            get {
                return ResourceManager.GetString("ErrorCannotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete.
        /// </summary>
        public static string ErrorCannotDelete {
            get {
                return ResourceManager.GetString("ErrorCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update.
        /// </summary>
        public static string ErrorCannotEdit {
            get {
                return ResourceManager.GetString("ErrorCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exist.
        /// </summary>
        public static string ErrorCodeExist {
            get {
                return ResourceManager.GetString("ErrorCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either start date or end date is not accepted.
        /// </summary>
        public static string ErrorDateWrong {
            get {
                return ResourceManager.GetString("ErrorDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date.
        /// </summary>
        public static string ErrorEndDateAfter {
            get {
                return ResourceManager.GetString("ErrorEndDateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher detail not found.
        /// </summary>
        public static string ErrorVoucherDetailNotFound {
            get {
                return ResourceManager.GetString("ErrorVoucherDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested voucher not found.
        /// </summary>
        public static string ErrorVoucherNotFound {
            get {
                return ResourceManager.GetString("ErrorVoucherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successfully.
        /// </summary>
        public static string InfoAddSuccess {
            get {
                return ResourceManager.GetString("InfoAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully.
        /// </summary>
        public static string InfoDeleteSuccess {
            get {
                return ResourceManager.GetString("InfoDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successfully.
        /// </summary>
        public static string InfoEditSuccess {
            get {
                return ResourceManager.GetString("InfoEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of codes.
        /// </summary>
        public static string InputAmount {
            get {
                return ResourceManager.GetString("InputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no vouchers.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not codes.
        /// </summary>
        public static string NoVoucherDetail {
            get {
                return ResourceManager.GetString("NoVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string NumberOrdinary {
            get {
                return ResourceManager.GetString("NumberOrdinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For bill total.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher list.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoucherDescription.
        /// </summary>
        public static string VoucherDescription {
            get {
                return ResourceManager.GetString("VoucherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher detail.
        /// </summary>
        public static string VoucherDetail {
            get {
                return ResourceManager.GetString("VoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher ID.
        /// </summary>
        public static string VoucherID {
            get {
                return ResourceManager.GetString("VoucherID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher name.
        /// </summary>
        public static string VoucherName {
            get {
                return ResourceManager.GetString("VoucherName", resourceCulture);
            }
        }
    }
}
